version: '3'

services:
    hubot:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - HUBOT_SLACK_TOKEN=$HUBOT
            - OWNER=gaku pro.gaku@gmail.com
            - BOTNAME=hey
            - DESCRIPTION=testbot
